source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RACAnimated_Example' do
  platform :ios, '9.0'
  pod 'RACAnimated', :path => '../'

  target 'RACAnimated_Tests' do
    inherit! :search_paths
  end
end


target 'RACAnimated-Example-AppleTV' do
    platform :tvos, '10.0'
    pod 'RACAnimated', :path => '../'
end
